@extends('layouts.app')

@section('content')
    <h1 class="text-3xl font-bold mb-8">Generate Report</h1>

    <!-- Generate Report Form -->
    <div class="bg-gray-800 p-6 rounded-lg shadow-lg">
        <form action="{{ route('reports.store') }}" method="POST">
            @csrf
            <!-- Report Name -->
            <div class="mb-4">
                <label for="name" class="block text-sm font-medium mb-2">Report Name</label>
                <input type="text" name="name" id="name" class="w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg focus:outline-none focus:border-blue-500" required>
            </div>
            <!-- Generated By -->
            <div class="mb-4">
                <label for="generated_by" class="block text-sm font-medium mb-2">Generated By</label>
                <input type="text" name="generated_by" id="generated_by" class="w-full px-4 py-2 bg-gray-700 border border-gray-600 rounded-lg focus:outline-none focus:border-blue-500" required>
            </div>
            <!-- Submit Button -->
            <div class="mt-6">
                <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 transition duration-200">
                    Generate Report
                </button>
            </div>
        </form>
    </div>
@endsection